### ISSUE TITLE
Getting error "Node dns module not supported in browsers."

### ISSUE THREAD

**Issue by raghu1286** [jspm/nodelibs-dns#1]
Hi,
I'm working on a project using jspm & reactjs, in that I included a react lib "react-validation-mixin" which internally has dependencies on "nodelibs-dns". On running the app in the browser the jspm babel runtime throws an error "Node dns module not supported in browsers." 

Any suggestions to fix this is greatly appreciated!

Thanks,
Raghav.

**Comment by guybedford** [comment]
Was this simply via `jspm install npm:react-validation-mixin`? It should work if it works with browserify. I can look into it if not.

**Comment by raghu1286** [comment]
yes it was via `jspm install`. I haven't tried using browserify though so not sure if it works with it.

**Comment by guybedford** [comment]
This is due to `npm:joi` requiring `npm:isemail` which uses dns.

I managed to fix this by removing the `isemail` dependency when installing joi, which can be added via an override in the package.json:

```
{
   "overrides": {
      "npm:joi@6.5.0": {
        "map": {
          "isemail": "@empty"
        }
      }
   }
}
```

**Comment by guybedford** [comment]
In short, yes dns doesn't work in browsers. Making it not fail so badly in browsers will be possible in future, but we're still getting there.

**Comment by raghu1286** [comment]
The override works.
Thanks a lot for looking into it.
